## Taller Integrador

In [3]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\usuario\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd

print(pd.__version__)

3.0.1

In [42]:
df = pd.read_csv("estudiantes_ml_2026_.csv")
df

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
1,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
3,Jorge Ramírez,41,Lima,Perú,M,avanzado,6,7.4,2,True,2024-09-01,True,2100,emprendimiento
4,Daniela Soto,29,Santiago,Chile,F,intermedio,10,6.8,2,True,2024-09-01,True,1500,cambio de carrera
5,Miguel Flores,37,Guadalajara,México,M,básico,4,4.1,1,False,2024-09-01,True,900,ascenso laboral
6,Laura Gómez,31,Cali,Colombia,F,básico,11,7.9,2,True,2024-09-01,False,0,cambio de carrera
7,Sebastián Castro,26,Buenos Aires,Argentina,M,intermedio,14,8.3,3,True,2024-09-01,True,1100,emprendimiento
8,Camila Vargas,33,Quito,Ecuador,F,básico,9,6.1,2,True,2024-09-01,True,700,primer empleo tech
9,Andrés Herrera,45,Barranquilla,Colombia,M,avanzado,5,7.2,2,True,2024-09-01,True,2500,emprendimiento
10,Paula Jiménez,27,Montevideo,Uruguay,F,básico,13,8.5,3,True,2024-09-01,False,0,cambio de carrera
11,Ricardo López,39,Caracas,Venezuela,M,intermedio,7,5.8,1,True,2024-09-01,True,600,cambio de carrera
12,Isabella Martínez,24,Medellín,Colombia,F,básico,16,9.4,3,True,2024-09-01,False,0,primer empleo tech
13,Fernando Díaz,52,Bogotá,Colombia,M,avanzado,3,NaN,0,False,2024-09-01,True,3200,emprendimiento
14,Natalia Romero,30,Cartagena,Colombia,F,intermedio,11,7.6,2,True,2024-09-01,True,1300,cambio de carrera
15,Diego Morales,28,La Paz,Bolivia,M,básico,10,6.4,2,True,2024-09-01,True,500,primer empleo tech
16,Sofía Reyes,35,Ciudad de México,México,F,intermedio,8,7.1,2,True,2024-09-01,True,1400,ascenso laboral
17,Alejandro Núñez,23,Bogotá,Colombia,M,básico,18,9.2,3,True,2024-09-01,False,0,primer empleo tech
18,Mariana Castillo,43,Asunción,Paraguay,F,avanzado,6,6.9,2,True,2024-09-01,True,1800,emprendimiento
19,Luis Prada,31,Cúcuta,Colombia,M,básico,9,NaN,1,True,2024-09-01,True,750,ascenso laboral
20,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
21,Andrea Fuentes,26,Bogotá,Colombia,F,intermedio,12,8.1,3,True,2024-09-01,False,0,cambio de carrera
22,Tomás Aguirre,38,Córdoba,Argentina,M,avanzado,5,7.8,2,True,2024-09-01,True,1900,emprendimiento
23,Valeria Peña,29,Bucaramanga,Colombia,F,básico,14,8.9,3,True,2024-09-01,False,0,primer empleo tech
24,José Moreno,47,Ciudad de Panamá,Panamá,M,intermedio,4,5.5,1,True,2024-09-01,True,2200,ascenso laboral

In [43]:
#Shape devuelve ( filas, columnas)
print(df.shape)
# nombres exactos de las columnas
print(df.columns.tolist())

(25, 14)
['nombre', 'edad', 'ciudad', 'pais', 'genero', 'nivel_previo', 'horas_estudio_semana', 'promedio', 'modulos_completados', 'activo', 'fecha_ingreso', 'trabaja_actualmente', 'salario_usd', 'objetivo']

In [44]:
df["nombre"]
#df["edad"]
print(df.loc[0,"nombre"])
print(df.loc[3, "promedio"])

Valentina Torres
7.4

In [45]:
df.head()
# me permite orientarme con respecto a la data que voy a trabajar

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
1,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
3,Jorge Ramírez,41,Lima,Perú,M,avanzado,6,7.4,2,True,2024-09-01,True,2100,emprendimiento
4,Daniela Soto,29,Santiago,Chile,F,intermedio,10,6.8,2,True,2024-09-01,True,1500,cambio de carrera

In [46]:
df.describe()

,edad,horas_estudio_semana,promedio,modulos_completados,salario_usd
count,25.000000,25.00000,23.000000,25.000000,25.000000
mean,33.400000,9.52000,7.269565,2.000000,1010.000000
std,7.697402,4.06325,1.458653,0.866025,898.841847
min,23.000000,3.00000,4.100000,0.000000,0.000000
25%,28.000000,6.00000,6.250000,1.000000,0.000000
50%,31.000000,9.00000,7.400000,2.000000,800.000000
75%,38.000000,12.00000,8.400000,3.000000,1500.000000
max,52.000000,18.00000,9.400000,3.000000,3200.000000

In [47]:
# Buscar de una base el promedio mayor a 8
df[df["promedio"] > 8]

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
7,Sebastián Castro,26,Buenos Aires,Argentina,M,intermedio,14,8.3,3,True,2024-09-01,True,1100,emprendimiento
10,Paula Jiménez,27,Montevideo,Uruguay,F,básico,13,8.5,3,True,2024-09-01,False,0,cambio de carrera
12,Isabella Martínez,24,Medellín,Colombia,F,básico,16,9.4,3,True,2024-09-01,False,0,primer empleo tech
17,Alejandro Núñez,23,Bogotá,Colombia,M,básico,18,9.2,3,True,2024-09-01,False,0,primer empleo tech
21,Andrea Fuentes,26,Bogotá,Colombia,F,intermedio,12,8.1,3,True,2024-09-01,False,0,cambio de carrera
23,Valeria Peña,29,Bucaramanga,Colombia,F,básico,14,8.9,3,True,2024-09-01,False,0,primer empleo tech

In [48]:
df[(df['promedio']>=8)&(df['activo'] == True)]

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
7,Sebastián Castro,26,Buenos Aires,Argentina,M,intermedio,14,8.3,3,True,2024-09-01,True,1100,emprendimiento
10,Paula Jiménez,27,Montevideo,Uruguay,F,básico,13,8.5,3,True,2024-09-01,False,0,cambio de carrera
12,Isabella Martínez,24,Medellín,Colombia,F,básico,16,9.4,3,True,2024-09-01,False,0,primer empleo tech
17,Alejandro Núñez,23,Bogotá,Colombia,M,básico,18,9.2,3,True,2024-09-01,False,0,primer empleo tech
21,Andrea Fuentes,26,Bogotá,Colombia,F,intermedio,12,8.1,3,True,2024-09-01,False,0,cambio de carrera
23,Valeria Peña,29,Bucaramanga,Colombia,F,básico,14,8.9,3,True,2024-09-01,False,0,primer empleo tech

In [49]:
# Limpiar dataset pero con criterio 
#detectar  hay algun problema

In [50]:
df.isnull().sum()

nombre                  0
edad                    0
ciudad                  0
pais                    0
genero                  0
nivel_previo            0
horas_estudio_semana    0
promedio                2
modulos_completados     0
activo                  0
fecha_ingreso           0
trabaja_actualmente     0
salario_usd             0
objetivo                0
dtype: int64

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre                25 non-null     str
 1   edad                  25 non-null     int64
 2   ciudad                25 non-null     str
 3   pais                  25 non-null     str
 4   genero                25 non-null     str
 5   nivel_previo          25 non-null     str
 6   horas_estudio_semana  25 non-null     int64
 7   promedio              23 non-null     float64
 8   modulos_completados   25 non-null     int64
 9   activo                25 non-null     bool
 10  fecha_ingreso         25 non-null     str
 11  trabaja_actualmente   25 non-null     bool
 12  salario_usd           25 non-null     int64
 13  objetivo              25 non-null     str
dtypes: bool(2), float64(1), int64(4), str(7)
memory usage: 2.5 KB